import type { SeoContent } from '@/components/pf/SeoLanding';
export const PUBLICATION_PAGES: Record<'zine'|'magazine', SeoContent> = {
 zine: {
  path:'/zine-flipbook',title:'Online Zine Maker from PDF — Free Zine Flipbook | Portfolia',
  description:'Publish your zine PDF as an online flipbook. Keep your artwork and page layouts, share a link or QR code, and embed your digital zine. Free to start.',
  h1:'Your zine,',h1Accent:'ready to pass around.',
  intro:'Bring your finished zine PDF online without rebuilding its pages. Keep the collage, illustration, photography and typography you designed, then share a reading link alongside your printed edition.',
  points:[{title:'Keep the handmade character',body:'The viewer presents your PDF artwork as designed. Simple and Studio offer different ways to read it; Portfolia does not redesign, impose or print the zine.'},{title:'A link beside the printed copy',body:'Put a downloadable QR code on a table card or back cover. Visitors can open your published zine on their own device.'},{title:'A useful contents panel',body:'Use named page ranges for stories, contributors or chapters. Each section gets a direct link without removing the rest of the publication.'}],
  steps:['Export a reading-order PDF from your design app. Check that scans and small type are legible.','Drop it here, preview it, then sign in to save and publish. Free supports one PDF up to 10 MB.','Share your link, download a QR code or use the embed code on your website.'],
  faqs:[{q:'Can I make a digital zine for free?',a:'You can host one finished PDF up to 10 MB on Free, including the flipbook, sharing link, QR code and embedding. You design the pages in your own app before uploading.'},{q:'Should I upload printer spreads or reading-order pages?',a:'Use a version arranged for reading. Printer-imposed sheets can put the pages out of sequence online. Export a separate digital copy and inspect it in the preview.'},{q:'Can I offer my zine as a PDF download?',a:'Yes. The owner can show or hide the PDF download button. Disabling the button does not prevent screenshots or other copying.'},{q:'Can I add scrapbook fold-outs or coloured tabs?',a:'These are proposed features and are not available yet. Current named projects provide a visual contents panel and links to page ranges.'},{q:'Can I publish more than one issue?',a:'Personal supports up to 10 separate portfolios or publications, each up to 50 MB with its own link. Free supports one PDF.'}],
 },
 magazine:{
  path:'/magazine-flipbook',title:'Digital Magazine Maker from PDF — Online Flipbook | Portfolia',
  description:'Turn your magazine PDF into an online flipbook. Publish an issue, link to articles, share or embed it, and view visit statistics. Start free with one PDF.',
  h1:'Your magazine,',h1Accent:'one link away.',
  intro:'Publish an independent magazine, student journal or editorial PDF in a focused reader. Preserve the issue you laid out and give readers a link that works alongside your website and print edition.',
  points:[{title:'An issue with its layout intact',body:'Your headings, images and editorial rhythm remain in the PDF. Choose Flipbook, Scroll or Page by page to suit the way you want readers to explore it.'},{title:'Direct links to articles',body:'Give articles named page ranges and share a link to their opening page. Readers can use visual contents to explore the rest of the issue.'},{title:'Share and understand visits',body:'Embed your issue on a website or share its link. Owners can see combined dashboard statistics and separate statistics for each uploaded publication.'}],
  steps:['Export your magazine in reading order with embedded fonts and images suitable for screens.','Upload the PDF, check the reading modes and add named article ranges. Sign in to publish.','Share the issue, embed it on your website and review its owner-only visit statistics.'],
  faqs:[{q:'Does Portfolia design magazine layouts?',a:'No. Prepare your magazine in your preferred design app and upload the completed PDF. Portfolia hosts and presents the publication.'},{q:'Will advertiser and article links stay clickable?',a:'External PDF links are clickable in Scroll and Page by page. They are not currently clickable in the flipbook, so offer another reading mode when links are essential.'},{q:'Can I update an issue after publishing?',a:'Yes. Replacing the PDF preserves the portfolio’s public address. Recreate named article ranges after replacement because page numbers may change.'},{q:'Can I see which individual articles were read?',a:'Current statistics count portfolio viewing sessions, estimated unique browsers and download clicks. They do not measure article reads, time spent or page-level engagement.'},{q:'Can I sell subscriptions or add videos inside the magazine?',a:'Portfolia does not currently provide reader subscriptions, paywalls or embedded video inside PDF pages. You can share a standard publication link or use Personal password and expiry controls.'}],
 }
};
export const PUBLICATION_ADVICE = {
 zine:[{title:'Prepare a digital edition that is comfortable to read',body:'A printed zine and its online counterpart can share the same artwork while needing different exports. Start with pages in reading order, including the cover. If the printed object uses folded sheets, check that you have not uploaded the printer’s imposition file. Review text over textured backgrounds and the resolution of scanned drawings at a normal screen size. Keep the original artwork and export a separate web copy when you need to reduce the file size.'},{title:'Give the reader context',body:'An introduction or colophon can explain the issue’s theme, contributors and credits. If different artists contribute sections, named projects can act as a contents list: enter a title and its first and last PDF page. The project link opens at that section while keeping the whole zine available. For a fair or exhibition, test your QR code from the final printed size and make sure the publication has been published before distributing it.'},{title:'Choose how the zine is shared',body:'Portfolia publications are unlisted by default, so you choose where to distribute the link. Search indexing is optional and does not create a discovery gallery. Embedding is available on Free and Personal, which can be useful for an artist website or collective’s issue page. Check that you have permission to publish contributed images and text. A publicly shared link can be passed on, even when search indexing is turned off.'}],
 magazine:[{title:'Make the issue readable beyond the design screen',body:'Inspect body text, captions, tables and image detail on a laptop and phone before sending the issue out. An impressive double-page layout on a large display can need zoom on a small one. Offer Scroll or Page by page alongside the flipbook when readers need selectable text or external links. The uploaded PDF controls the content and layout; the viewer does not rewrite articles or recover detail lost during export.'},{title:'Organise issues and articles clearly',body:'Use a consistent issue title and date in the PDF filename and profile details. Named project ranges can become an article contents list, with short descriptive labels that distinguish each story. Each uploaded publication has its own link, so separate issues can remain available independently within the Personal plan’s allowance. Portfolia does not yet provide a public bookshelf or magazine archive page. An existing website can link to or embed individual issues.'},{title:'Use statistics for what they actually measure',body:'The dashboard combines visits across the owner’s publications. A publication’s editor and owner-only viewing panel show its own statistics. A visit is a viewing session, not a confirmed read of every page, and download clicks are not completed downloads. These figures can help you compare interest in different issues, but they do not establish article completion, named reader identities or advertising impressions. Page-level engagement is a possible future addition.'}]
};
